name: run main.py

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Python packages
        run: |
          pip install scratchattach requests schedule pillow pyautogui opencv-python
    
      - name: Verify packages
        run: |
          pip list
          pip show scratchattach
          pip show requests
          pip show pillow

      - name: Run main.py
        env:
          SECRET: ${{ secrets.SECRET }} # Pass secret as environment variable
        run: python ss.py
        
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Commit and push changes
        run: |
          git add captured_*.png
          git commit -m 'Add screenshot from GitHub Actions'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
