name: run main.py

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Python packages
        run: |
          pip install scratchattach requests schedule g4f
          
      - name: Verify packages
        run: |
          pip list
          pip show scratchattach
          pip show requests
          pip show schedule
          pip show g4f

      - name: Run main.py
        env:
          SECRET: ${{ secrets.SECRET }} # Pass secret as environment variable
        run: python main.py
